### ISSUE TITLE
If my code extends your life, please say thanks to the GREAT authors of GS, then me.  :-)

### ISSUE THREAD

**Issue by yuedajiong** [graphdeco-inria/gaussian-splatting#350]
rewrite, one night, just first version.  
convergeable

done:
 1. continue to optimize the code: correct, simple.  <500 lines even <400 lines.      (2023-10-21, corret!!!, mesh!!!)
todo:
 2. optimize algorithm.   such as batchfiy, multi-object, pose-esitmation internal, priori/single-image(not dream-gauss); better viewer for this gauss data.
 3. new algo, especial ‘Friendly’ to later mesh-extraction.
 

new code: (2023-11-15)

[superi.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13366155/superi.zip)

**Comment by 1346052851** [comment]
i run your code , generate below error

```
iteration=000010  loss=0.000001
...
iteration=000600  loss=0.000004
Traceback (most recent call last):
  File "/mnt/d/Software/AI/gaus1/2310/wsl_cuda118/train2.py", line 456, in <module>
    main()
  
  File "/mnt/d/Software/AI/gaus1/2310/wsl_cuda118/train2.py", line 436, in main
    loss.backward()
  
  File "/opt/conda/envs/cuda118/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  
  File "/opt/conda/envs/cuda118/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function _RasterizeGaussiansBackward returned an invalid gradient at index 2 - got [0, 0, 3] 
but expected shape compatible with [0, 16, 3]
```

**Comment by yuedajiong** [comment]
@1346052851 

fixed a little bug:  data-process,  fore+back, *255.
tested, it is OK.    wizard.zip is my custom data.

[gs.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13059398/gs.py.txt)

[wizard.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13059395/wizard.zip)


and , mesh (from dream-gauss)  is under debug,  it looks the shape is ok.
[ms.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13059403/ms.py.txt)

**Comment by WWmore** [comment]
> rewrite, one night, just first version. convergeable
> 
> done:
> 
> 1. continue to optimize the code: correct, simple.  <500 lines even <400 lines.      (2023-10-21, corret!!!, mesh!!!)
>    todo:
> 2. optimize algorithm.   such as batchfiy, multi-object, pose-esitmation internal, priori/single-image(not dream-gauss); better viewer for this gauss data.
> 3. new algo, especial ‘Friendly’ to later mesh-extraction.
> 
> [gs.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13059589/gs.py.txt) [ms.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13059590/ms.py.txt)
> 
> [wizard.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13059588/wizard.zip)

Thanks for your work. Could you please show how the output mesh of your wizard example look like? I run the code followd by convert.py --> train.py --> gs.py, which produces gs_shape.obj, gs_texture.obj and .mtl. But unfortunately the mesh looks quite messy and far from the wizard shape.

**Comment by 520jz** [comment]
> > rewrite, one night, just first version. convergeable
> > done:
> > 
> > 1. continue to optimize the code: correct, simple.  <500 lines even <400 lines.      (2023-10-21, corret!!!, mesh!!!)
> >    todo:
> > 2. optimize algorithm.   such as batchfiy, multi-object, pose-esitmation internal, priori/single-image(not dream-gauss); better viewer for this gauss data.
> > 3. new algo, especial ‘Friendly’ to later mesh-extraction.
> > 
> > [gs.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13059589/gs.py.txt) [ms.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13059590/ms.py.txt)
> > [wizard.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13059588/wizard.zip)
> 
> Thanks for your work. Could you please show how the output mesh of your wizard example look like? I run the code followd by convert.py --> train.py --> gs.py, which produces gs_shape.obj, gs_texture.obj and .mtl. But unfortunately the mesh looks quite messy and far from the wizard shape.

Hi! I have the same problem as you. Did you solve it？

**Comment by WWmore** [comment]
> > > rewrite, one night, just first version. convergeable
> > > done:
> > > 
> > > 1. continue to optimize the code: correct, simple.  <500 lines even <400 lines.      (2023-10-21, corret!!!, mesh!!!)
> > >    todo:
> > > 2. optimize algorithm.   such as batchfiy, multi-object, pose-esitmation internal, priori/single-image(not dream-gauss); better viewer for this gauss data.
> > > 3. new algo, especial ‘Friendly’ to later mesh-extraction.
> > > 
> > > [gs.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13059589/gs.py.txt) [ms.py.txt](https://github.com/graphdeco-inria/gaussian-splatting/files/13059590/ms.py.txt)
> > > [wizard.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13059588/wizard.zip)
> > 
> > 
> > Thanks for your work. Could you please show how the output mesh of your wizard example look like? I run the code followd by convert.py --> train.py --> gs.py, which produces gs_shape.obj, gs_texture.obj and .mtl. But unfortunately the mesh looks quite messy and far from the wizard shape.
> 
> Hi! I have the same problem as you. Did you solve it？

Nope...

**Comment by yuedajiong** [comment]
@WWmore  @520jz 

hi, guys, there is not mesh-extraction in this official gaussian-splatting repo.   
I used mesh-extraction code from DreamGaussian.

No any debug, no any optimization, so far.   so, the quality of mesh is so so.   :-(

I will do this optimization work, in later a few days.

any progressing,  tell you guys.

**Comment by 520jz** [comment]
> @WWmore @520jz
> 
> hi, guys, there is not mesh-extraction in this official gaussian-splatting repo. I used mesh-extraction code from DreamGaussian.
> 
> No any debug, no any optimization, so far. so, the quality of mesh is so so. :-(
> 
> I will do this optimization work, in later a few days.
> 
> any progressing, tell you guys.

Oh！Thank you very much！

**Comment by yuedajiong** [comment]
you can use this GS to generate ‘coarse’ mesh， then use other 'strong-fitting' algorithms to optimize:   DreamGauss stage 2,  DMTet,  brute-force-fitting especial texuture in pytorch3d sampels,  other interpolation algo, ...

in GS, if your GPU is not a problem, your can tune GS to samller Gauss points to get better result.

good luck.

**Comment by yuedajiong** [comment]
this gaussian-splatting is not born for surface/mesh.    
not only representation, but also training.   
the gauss point are not trend to converge to the surface of object.

the direct surface reconstuciton algorithms:  SDF/UDF, NeuS/NeuS2/Neus2++, ...

**Comment by 520jz** [comment]
> you can use this GS to generate ‘coarse’ mesh， then use other 'strong-fitting' algorithms to optimize: DreamGauss stage 2, DMTet, brute-force-fitting especial texuture in pytorch3d sampels, other interpolation algo, ...
> 
> in GS, if your GPU is not a problem, your can tune GS to samller Gauss points to get better result.
> 
> good luck.

great answer！Thank you！

**Comment by HungNgoCT** [comment]
@yuedajiong ,

Mesh I obtained after running gs.

![gs](https://github.com/graphdeco-inria/gaussian-splatting/assets/110378166/7f09e75c-ada4-4170-8bef-2d0315f01496)

Any advice?

**Comment by yuedajiong** [comment]
@cywm39  @1346052851

new code is OK to run.

fixed by:  (can not comment this functio)

    def get_covariance(self, scaling_modifier = 1):  #call in render, must have
        return self.covariance_activation(self.get_scaling, scaling_modifier, self._rotation)  #build_covariance_from_scaling_rotation


I am still woking on the mesh-extranction optimization.   (there is not simple and 'GOOD' way to extract mesh from GS points)
I added 'flat' logic to single gauss point, and 'flat' the gauss-points to close to surface. 
If you guys are interested in this trick,  I can mail detials to you.

**Comment by juicee030** [comment]
> rewrite, one night, just first version. convergeable
> 
> done:
> 
> 1. continue to optimize the code: correct, simple.  <500 lines even <400 lines.      (2023-10-21, corret!!!, mesh!!!)
>    todo:
> 2. optimize algorithm.   such as batchfiy, multi-object, pose-esitmation internal, priori/single-image(not dream-gauss); better viewer for this gauss data.
> 3. new algo, especial ‘Friendly’ to later mesh-extraction.
> 
> new code: (2023-11-15)
> 
> [superi.zip](https://github.com/graphdeco-inria/gaussian-splatting/files/13366155/superi.zip)

I still can't get the correct mesh even with the new code :-(

**Comment by yuedajiong** [comment]
@juicee030    you can try other GS-mesh code firstly, like dream-gaussian (my mesh code is modified from it).
   I can train the GS and quality is OK, but the extracted mesh is NOT OK：not only texture, even pure shape. I checked the code, the extract_fields function can not extract correctly.
  I am still working on the problem, I will upload later code, extrac a better mesh, at least product-level.
